Minor changes for consistency

diff --git a/bin/tools/cache b/bin/tools/cache
--- a/bin/tools/cache
+++ b/bin/tools/cache
@@ -5,6 +5,25 @@
 # modifications for AXE
 # Credit to http://stackoverflow.com/users/1916449/arekolek
 
+##############################################################################
+# Shell Behaviour
+##############################################################################
+
+# Check for unbound variables being used
+# set -o nounset
+
+# Exit is a bad command is attempted. If you're going to handle errors then
+# leave this disabled
+# set -o errexit
+
+# The return value of a pipeline is the status of the last command to exit with
+# a non-zero status, or zero if no command exited with a non-zero status
+# set -o pipefail
+
+##############################################################################
+# Main Script
+##############################################################################
+
 # hash all arguments
 KEY="$@"
 CACHE_ROOT=/tmp/axecache
@@ -26,13 +45,13 @@ done
 cache_file="${CACHE_ROOT}/command_cache.$(echo -n "$KEY" | md5sum | awk '{print $1}')"
 
 # If we have a cache check it's age and if not aged out then use it.
-if [ -f $cache_file ]; then
-    cache_age=$(( $(date +%s) - $(stat -L --format %Y $cache_file) ))
+if [ -f ${cache_file} ]; then
+    cache_age=$(( $(date +%s) - $(stat -L --format %Y ${cache_file}) ))
     if [ $cache_age -lt $MAX_AGE ]; then
-        cat $cache_file
+        cat ${cache_file}
     else
-        $@ | tee $cache_file
+        $@ | tee ${cache_file}
     fi
 else
-    $@ | tee $cache_file
+    $@ | tee ${cache_file}
 fi
